### ISSUE TITLE
recompiling the CURL subproject (marmalde OSX XCode)

### ISSUE THREAD

**Issue by fiachra** [bradenmacdonald/MarmaladeHttpUtils#1]
Thanks so much for this repo. It's been really help for getting some work implemented in one of my projects. I know it's been a while since anyone looked at it but I'm having a problem. 

Currently the libcurl build included doesn't have a lib binary for arm64. Since the subproject is included I didn't think this would be a problem. I thought I could fire up the MKB of the subproject, switch to GCC ARCH64  and chase down any lingering type size problems. 

The problem I'm having is that no matter which compiler I choose, Im getting the same 2 errors,

MarmaladeHttpUtils/subprojects/curl/source/urldata.h:1420:3: Unknown type name 'curl_xferinfo_callback'

MarmaladeHttpUtils/subprojects/curl/source/urldata.h:1642:30: Field has incomplete type 'struct curl_tlssessioninfo'

Now both of these are defined in curl/curl.h which is included in urldata.h on line 175. Can anyone there see what I'm doing wrong?

**Comment by bradenmacdonald** [comment]
Is it possible you have another version of curl on your import path somewhere? Maybe when importing `#include <curl/curl.h>`, it's getting pulled from somewhere else on your system?

**Comment by fiachra** [comment]
Thanks you! You put me on the right track. Your curl subproject mkb file has the line "subproject curl" in it. I'm assuming this covers including the necessary headers and since the curl.mkf file is right there in the same dir, it was not problem. I'm not sure when the change occurred but marmalade now has curl in the third_party dir so those headers were being included instead. 

Just to be sure the correct lib was included I had to do the following:

subprojects
{
    ../../subprojects/curl/curl
}

It seems overkill but just using ../curl/curl still included the wrong lib headers. With the above change everything works correctly now.

Thanks again,

Fiachra.
